### PR TITLE
ODoE Enhancements

### PR DESCRIPTION
**Pull request by sotorrio1**
Started adding some UI elements to accommodate the new version of ODoE. Everything depends on next release of psuade-lite (1.9.0). Takes care of issue #905

### CODE REVIEW

**Comment by sotorrio1** [comment]
@mirandamartin You don't need to review this until our demo next week. Just a reminder, psuade-lite 1.9.0 is now released and ready to install as a conda package. The new version is needed for this version of ODoE to work

**Comment by sotorrio1** [comment]
@mirandamartin did you get a chance to check this? Thanks!

**Comment by mirandamartin** [comment]
@sotorrio1 I haven't had a chance yet but I hope to by the end of the week. Sorry about the delay.

**Comment by sotorrio1** [comment]
@mirandamartin no worries! Just checking

**Comment by mirandamartin** [comment]
@sotorrio1 I was running through the two examples in the documentation, and most things worked great, but I had a few issues -- 
1. The View button for the Evaluation Set didn't work for me (Nothing happened when clicked). In contrast, the view button for the Candidate Set worked normally. 
2. Trying to use E-optimality, I get this error:
2022-02-04 16:21:49,249 - CRITICAL - foqus.foqus_lib.foqus - unhandled exception
Traceback (most recent call last):
  File "/Users/mgmartin/Desktop/FOQUS-Other/FOQUS-sotorrio/FOQUS/foqus_lib/gui/sdoe/sdoeSetupFrame.py", line 2561, in runOdoe
    optCriterion,
UnboundLocalError: local variable 'optCriterion' referenced before assignment
This error occurs whether I select Fisher or Bayesian for Statistical Method. I reinstalled psuade-lite before running all of these tests and when I look at its information it says it's version 1.9.0, so I don't think that's the problem (but who knows).

**Comment by sotorrio1** [comment]
@mirandamartin Good catches both of them! Just pushed the changes to fix those

**Review by mirandamartin — APPROVED** [review]
Looks good now, thanks!

**Pull request merged**
