### PR TITLE
Adding type annotations to SDoE

### PR DESCRIPTION
**Pull request by sotorrio1**
## Fixes/Addresses:

Addresses issue #1111 

## Summary/Motivation:
Adding type annotations to all SDoE files

## Changes proposed in this PR:
- adding SDoE type annotations
- adding some function descriptions 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the copyright and license terms described in the LICENSE.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by sotorrio1** [comment]
@lbianchi-lbl & @franflame I'm no expert on type annotations but hopefully this is a good starting point.

**Review by franflame — DISMISSED** [review]

**Review by lbianchi-lbl — COMMENTED** [review]
Thanks @sotorrio1 for doing the work. This looks good as it is. One thing I'd consider changing before merging would be to use `typing.List` and `typing.Dict` (instead of `list` and `dict` respectively[1]) to be able to add information about the type of contained items, e.g. 

```py
from typing import List
...
def split_string(s: str) -> List[str]:
   ...
```

Concretely, this would be useful to distinguish between e.g. `List[int]`, `List[str]`, etc as IIRC both show up in the SDoE function arguments.

---

[1]: This in not needed with Python 3.9+ as the builtin `list`, `dict`, `tuple` etc support the type annotation `[]` directly, but we're currently still maintaining compatibility with Python 3.8.

**Comment by sotorrio1** [comment]
> Thanks @sotorrio1 for doing the work. This looks good as it is. One thing I'd consider changing before merging would be to use `typing.List` and `typing.Dict` (instead of `list` and `dict` respectively) to be able to add information about the type of contained items, e.g.
> 
> ```python
> from typing import List
> ...
> def split_string(s: str) -> List[str]:
>    ...
> ```
> 
> Concretely, this would be useful to distinguish between e.g. `List[int]`, `List[str]`, etc as IIRC both show up in the SDoE function arguments.
@lbianchi-lbl Sounds good! I'll take care of that. Thanks!

**Review by lbianchi-lbl — APPROVED** [review]
Let's get this in now, and move any additional changes to future PR(s).

**Pull request merged**
