### PR TITLE
Remove time index from variable browser

### PR DESCRIPTION
**Pull request by eslickj**
Also convert column list for calculated columns to drag and drop

### CODE REVIEW

**Comment by fsoepyan** [comment]
Variable explorer works, and the time index is no longer there.

**Comment by fsoepyan** [comment]
The "Calculated Column" list does have a drag and drop feature, but where can we drop the item to?

**Comment by eslickj** [comment]
@fsoepyan you should be able to drop the column into the box where you enter the calculation expression.

**Comment by eslickj** [comment]
Not sure what happened, but this PR seems to be incomplete. I'm just going to tack it onto something else I'm fixing and close this.

**Pull request closed without merging**
