### PR TITLE
Added sdoe tests

### PR DESCRIPTION
**Pull request by franflame**
Added sdoe tests, configuration files, and sample candidates

Resolves: #1083 

## Summary/Motivation:

Increase test coverage for sdoe core functionalities 

## Changes proposed in this PR:
- add tests for `distance.py`, `irsf.py`, `usf.py`, `nusf.py`, and `sdoe.py`
- add `config.ini` and `candidates.csv` files to test `sdoe.run()` 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the copyright and license terms described in the LICENSE.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by ksbeattie** [comment]
The .py files should get the updated copyright header once PR #1099 is merged.

**Comment by sotorrio1** [comment]
LGTM!

**Review by sotorrio1 — APPROVED** [review]
LGTM!

**Review by lbianchi-lbl — CHANGES_REQUESTED** [review]
Blocking this until the copyright header has been added.

**Pull request merged**
