### PR TITLE
Read from simple file

### PR DESCRIPTION
**Pull request by sotorrio1**
This PR gets the code to the original version where loading all samples from a single PSUADE file worked. It should fix issue #708

### CODE REVIEW

**Comment by fsoepyan** [comment]
- I downloaded FOQUS from this PR.
- I installed FOQUS using the developers' method.
- I opened FOQUS, and went to the UQ tab.
- I managed to successfully upload the CSV file.
- I managed to successfully run the samples.
- But when I clicked "Analyze", I get this error message:

image

**Comment by fsoepyan** [comment]
Another thing I noticed:
- If I upload this CSV file (I saved the file as an Excel file, because I cannot upload CSV files to GitHub), with the old format, I managed to upload the file to the UQ tab:

[example_samples.xlsx](https://github.com/CCSI-Toolset/FOQUS/files/4553412/example_samples.xlsx)

- But if I upload this CSV file (I saved the file as an Excel file, because I cannot upload CSV files to GitHub), with the new format recommended by @anujad95, I cannot upload the file to the UQ tab:

[example_samples_04_29_2020.xlsx](https://github.com/CCSI-Toolset/FOQUS/files/4553413/example_samples_04_29_2020.xlsx)

image

**Comment by anujad95** [comment]
@fsoepyan the format which i had specified only applies for samples to be uploaded for optimization. The format for uq csv samples will not change.

**Comment by fsoepyan** [comment]
@anujad95: Thank you for the clarification.

Then in that case:
- Good news: We can upload and run the CSV file successfully in the UQ tab.
- Bad news: We cannot "Analyze" the CSV samples, as this produces an error message.

**Comment by sotorrio1** [comment]
@jmorgan29 would you mind to review when you get a chance? Thanks!

**Pull request merged**
