### PR TITLE
Batch File and requirements.txt

### PR DESCRIPTION
**Pull request by eslickj**
I added requirements.txt which I hope will fix the weird import errors that we were getting with requirements installed from setup.py.  Installing those added a step to the install instructions.

I also took a shot at generating a batch file on windows at the end of setup.py.  It works good for me, but several people will probably need to try it to ensure it works for different setups.  I think as long as it looks reasonable it's probably fine to merge then test.

I also dropped the enumerated type value that was causing problems  with adodbapi.  I don't know why sometimes the enum is there sometimes and not others.  Maybe if has something to do with where you get your pacakages, but I replaced it with the number to avoid problems.

@boverhof, I added python-dateutil==2.5.0 to requirements because I have a problem where the latest version makes TurbineClient complain about the version being to old.  They may have removed something you are using.

### CODE REVIEW

**Comment by eslickj** [comment]
I accidentally branched PR #367 off this so it got merged when that did

**Comment by CSRussell2319** [comment]
The batch file seemed to be missing an ending quotation when I tried using it. Also, it might be better to use /K instead of /C since the user can't see any error messages from launching foqus if it closes automatically (I had an error about tqdm not being installed that I had to manually check since the cmd window closed before I could read the error). This could be done by creating an additional file labeled "Debug" that has the /K included. You removed the option to install turbine via ssh, which is needed for my corporate proxy to work. The batch file should be added to the git ignore list if it hasn't been already.

**Comment by ksbeattie** [comment]
@CSRussell2319, seems like your suggestion might be worth following up on.  Is it captured in another issue or PR?

**Comment by CSRussell2319** [comment]
No, I haven't opened any other issue to address this

**Comment by ksbeattie** [comment]
I created issue #388 for us to follow up on, if desired.

**Pull request merged**
