### PR TITLE
New documentation of SDoE module with description of process for the NUSF capability 

### PR DESCRIPTION
**Pull request by candcook**
I have done an overhaul of the documentation:
- I removed some unnecessary preamble about SDoE
- I added some figures in the introduction to describe the flow of designs for different objectives
- I reorganized the "Basic" section to distinguish between the USF and NUSF
- I updated figures to reflect the new look of the GUI
- I added the section "Basic Steps for a Non-Uniform Space Design"
- I updated the examples section to make clear what kinds of designs are being created.

### CODE REVIEW

**Comment by sotorrio1** [comment]
Related to #651 and #653

**Comment by candcook** [comment]
Hi Pedro,

I have made the changes that you requested. Do I create a new PR for the changes, or somehow connect it to the previous one?
I don’t think that I have done this before.

Thanks,
Christine

**Comment by candcook** [comment]
Updated to reflect changes Pedro requested

**Comment by sotorrio1** [comment]
@candcook you did it right, no need to create another PR. Your changes are pushed to the same PR

**Comment by candcook** [comment]
Great – it looked like there was a hold on the new updates until I did something with the request for changes – glad it worked.

Thanks,
Christine

**Pull request merged**
