### PR TITLE
Improving SDoE GUI Testing Coverage

### PR DESCRIPTION
**Pull request by franflame**
## Fixes/Addresses:

#1218

## Summary/Motivation:

Increasing coverage for SDoE GUI testing. 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the copyright and license terms described in the LICENSE.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
Sketch of how the `qtbot` code inside the `SDoEAnalysisDialog` might look like:

```py
# set values, options, etc according to tutorial

# find the "Run SDoE" button and assign it to local variable
# it might be necessary to narrow the search area using qtbot.searching_within(group_box="...")
run_button = qtbot.locate("Run SDoE")

# define callable that returns True when SDoE has finished running
def run_button_available() -> bool:
    return run_button.currentText() == "Run SDoE"

# the timeout is in ms, and it might need to be adjusted according to the NUSF settings
qtbot.wait_until(run_button_available, timeout=300_000)
```

**Comment by franflame** [comment]
current_available_tutorial_files

The file used for the [Example NUSF-2 tutorial](https://foqus.readthedocs.io/en/stable/chapt_sdoe/examples-nonuniform.html#example-nusf-2-constructing-non-uniform-space-filling-for-a-4-input-carbon-capture-example), “CCSIex.csv” doesn't exist in the FOQUS repository anymore. I checked all of the available tutorial files in the same directory and none of them have the same data as CCSIex.csv, not sure how we want to proceed with this

**Comment by sotorrio1** [comment]
@franflame thanks for this. I've reached out to Abby at LANL and hopefully we can get a copy of that file (I don't have it myself either...)

**Comment by sotorrio1** [comment]
@franflame After reaching out to Abby I actually realized we can generate our own candidate set given the min and max values for each one of the input variables, using an existing feature within SDoE that leverages psuade-lite. 
Please use this file [CCSIex.csv](https://github.com/user-attachments/files/15594992/CCSIex.csv) I just generated and let me know if that works with the testing.

**Comment by franflame** [comment]
@sotorrio1 I just tested it and I can confirm that CCSIex.csv is working! I'm now finishing up the testing code for the NUSF-2 tutorial.

**Comment by lbianchi-lbl** [comment]
@lbianchi-lbl will write a set of commands that @sotorrio1 can use to reproduce the failure locally, and hopefully provide some insight into what might be going wrong.

**Pull request merged**
