### PR TITLE
Fixing SDOE plotting

### PR DESCRIPTION
**Pull request by sotorrio1**
Should take care of issue #706.

### CODE REVIEW

**Comment by ksbeattie** [comment]
@atowfiq, any news on this?

**Comment by sotorrio1** [comment]
@atowfiq could you please review? Thanks! :)

**Comment by atowfiq** [comment]
I will review and report it by tomorrow.

Thanks for the reminder.

**Comment by atowfiq** [comment]
I reviewed the latest CCSI-Toolset/FOQUS.  I left my comments for issue
#707 on GitHub

Thanks,

**Pull request merged**
