### PR TITLE
Updates to SDoE Documentation Examples Pages

### PR DESCRIPTION
**Pull request by mirandamartin**
## Fixes/Addresses:

Updated examples in SDoE documentation (updating screenshots, example files, results).

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the copyright and license terms described in the LICENSE.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by sotorrio1 — APPROVED** [review]
LGTM

**Comment by ksbeattie** [comment]
@sotorrio1 a/o @mirandamartin is this part of any of our milestones?

**Comment by ksbeattie** [comment]
> @sotorrio1 a/o @mirandamartin is this part of any of our milestones?

I've placed this under milestone https://github.com/CCSI-Toolset/FOQUS/milestone/37, which is somewhat of a stretch, but feel free to disagree.

**Comment by sotorrio1** [comment]
> > @sotorrio1 a/o @mirandamartin is this part of any of our milestones?
> 
> I've placed this under milestone https://github.com/CCSI-Toolset/FOQUS/milestone/37, which is somewhat of a stretch, but feel free to disagree.

It's kind of a stretch but I'm OK with it. I don't believe Miranda's work responded to any specific milestones, it was more something we needed to do to reflect latest updates to the GUI and visualizations...

**Pull request merged**
