### PR TITLE
Fix ACOSSO and BSS-ANOVA

### PR DESCRIPTION
**Pull request by eslickj**
When we updated the results format to Pandas we lost the exportVarsCSV function.  I guess since it has been over a year sicne that change was made it's safe to say ACOSSO and BSS-ANOVA aren't used much.

Fix for issue #433 and #434.

### CODE REVIEW

**Comment by fsoepyan** [comment]
- I managed to generate the surrogate models
- But when I ran FOQUS using these surrogate models, FOQUS failed with a simulation code 20
- When I generated ACOSSO, this is the message I got in the Surrogates tab:

------------------------------------
Starting ACOSSO

Model File:     acosso_fit.rds
Py File (UQ):   acosso_example_uq.py
RScript Path:   C:\Program Files\R\R-3.5.1\bin\Rscript.exe
Sub-directory:  acosso
X data file:    acosso\xdat.csv
Y data file:    acosso\ydat.csv
Order:          2
CV:             bic
------------------------------------
Exporting Data...
    Inputs: ["stupid.x1", "stupid.x2", "stupid.x3"]
    Output: ["stupid.y"]
Running ACOSSO...
Process completed code: 0
Wrote Python driver file: acosso\acosso_example_uq.py

- When I generated BSS-ANOVA, this is the message I got in the Surrogates tab:

------------------------------------
Starting BSS-ANOVA

Model File:      bssanova_fit.rds
Py File (UQ):    bssanova_example_uq.py
RScript Path:    C:\Program Files\R\R-3.5.1\bin\Rscript.exe
Sub-directory:   bssanova
X data file:     bssanova\xdat.csv
Y data file:     bssanova\ydat.csv
Burn In:         0
MCMC Iterations: 1000
Record Interval: 1
N. Terms:        25
Order:           2
Prior Prob.:     0.5
bte:             [0, 1000, 1]
------------------------------------
Exporting Data...
    Inputs: ["stupid.x1", "stupid.x2", "stupid.x3"]
    Output: ["stupid.y"]
Running BSS-ANOVA...
Process completed code: 1
Error in if (highpt == 0) { : missing value where TRUE/FALSE needed
Calls: bssanova -> BSSANOVA
Execution halted
Wrote Python driver file: bssanova\bssanova_example_uq.py

**Comment by eslickj** [comment]
I don't think ACOSSO and BSS-ANOVA ever generated a flowsheet plugin.  If you look closely they just generate a UQ plugin that you can't run in a flowsheet.

**Comment by fsoepyan** [comment]
Actually, when I used the Surrogates tab to generate ACOSSO and BSS-ANOVA, the fs PY files did get generated, and they were available under "Plugin" in the Flowsheet Node Editor.

I checked my FOQUS working directory, and these PY files are also available in the "user_plugins" folder.

There is also an "acosso" folder and a "bss-anova" folder in my FOQUS working directory that contains the uq PY files.

If the fs PY plugins are not meant to be used in Flowsheet, then there is no reason not to approve this PR.

**Comment by fsoepyan** [comment]
@ngbrenda or @sotorrio1: If either of you can confirm that this PR works, then can you please approve and merge this PR? Thank you!

**Comment by sotorrio1** [comment]
@fsoepyan I haven't used ACOSSO or BSS-ANOVA before. What do you want me to test exactly?

**Pull request merged**
