### PR TITLE
Loading sample from CSV file

### PR DESCRIPTION
**Pull request by sotorrio1**
… file

## Fixes/Addresses:

Fixes issue #671 where the user tries to load a sample with a CSV file and it fails. 

## Summary/Motivation:
In the UQ module there are different ways to generate simulations, one of them being loading the entire sample in a CSV or .smp format. Loading the sample in CSV format wasn't working properly and it required a small tweak to the function being used. 

When loading a sample from csv file, user should make sure they can launch the simulation and then after clicking "Analyze" the UQ Analysis Dialog menu should pop up. 

## Changes proposed in this PR:
- Depending on sample file being used, different function is used

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the copyright and license terms described in the LICENSE.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by sotorrio1** [comment]
@jmorgan29 Let me know if you need a little bit more background on this issue. We can jump into a quick call if needed :)
Thanks!

**Comment by ksbeattie** [comment]
@jmorgan29 will have a chance to review this PR this week?  (We hope to create the RC for the Sept release next week).

**Comment by ksbeattie** [comment]
@jmorgan29 any news?

**Comment by lbianchi-lbl** [comment]
@jmorgan29 is on it and should be straightforward to check. Otherwise, the same applies in that this PR is fixing a pre-existing problem and it might be better to just merge it in before the release.

**Review by jmorgan29 — APPROVED** [review]
Apologies for the delay, as I had overlooked the original request. I implemented the change for the PR and it fixed the issue with not being able to select the 'Analyze' button for an ensemble generated using a sample from a csv file.

**Pull request merged**
