### PR TITLE
Fix NUSF with history

### PR DESCRIPTION
**Pull request by pn51**
Addresses issue #969.

### CODE REVIEW

**Comment by ksbeattie** [comment]
Hey @pn51, you should be able to fix the "black" failure by just running the command `black` on the one file you modified, then commit/push that change.

**Comment by mirandamartin** [comment]
@pn51 Phan, would you have time tomorrow or Wednesday to walk me through your changes? I'd like to understand more of what you and Pedro did to fix the code.

**Review by sotorrio1 — APPROVED** [review]
Just tested running NUSF with previous data file and everything works as expected.

**Review by mirandamartin — APPROVED** [review]
Approved, though I couldn't tell much of a difference in designs before the most recent fix and after. We should reexamine in the future.

**Review by sotorrio1 — APPROVED** [review]
LGTM

**Pull request merged**
