### PR TITLE
Reorganization of the "examples" folder

### PR DESCRIPTION
**Pull request by fsoepyan**
This is for #558.

In the "examples" folder, I created 3 subfolders:
- tutorial_files
- test_files
- other_files

However, I did not delete any of the existing subfolders and files in the "examples" folder.

### CODE REVIEW

**Comment by fsoepyan** [comment]
@sotorrio1: Thank you for the suggestions.

I have some ideas and questions:
- I will go through the "examples" folder, delete the files (in my fork) that I know we don't use anymore.
- I think the E1 to E4 files from the "examples/ALAMO" folder can be deleted.
- Should we delete the entire "examples/DRMBuilder" folder, or is there a place where we can transfer this folder? I'm asking because I know DRMBuilder is no longer part of FOQUS.
- In my fork, I already transferred the 3 files that @anujad95 created for the new heat integration tutorial to the new folder "examples/tutorial_files/Heat_Integration". Can we delete the rest of the files in the "examples/Heat_Integration" folder?
- Can we delete the contents of "examples/iREVEAL"? Two of the files (boiler and boiler_rom) are in the iRevealLite repository. I'm asking because I know iReveal is no longer part of FOQUS.
- @anujad95: Is there a tutorial in the documentation for optimization using Snobfit? If there is, I will move the Snobfit files into the "examples/tutorial_files/Optimization" folder. Otherwise, I will move the Snobfit files into the "examples/test_files/Optimization_Snobfit" folder.
- For the rest of the files in "examples/Optimization", I think we can delete them.
- I already transferred the files in "examples/OUU", "examples/PYOMO", and "examples/SDOE" into the appropriate folders in my fork.
- I think we can delete the contents of the "examples/Recycle" folder. I already transferred the 1 file that the tutorial use to the appropriate folder in my fork.
- Can we delete the "examples/Scaling_Spreadsheet" folder?
- Do we want to keep the contents of the "examples/Smoke Tests"? If so, I propose moving this folder into "examples/other_files" in my fork.
- @sotorrio1: For the UQ folder, I already transferred 6 files into the "examples/tutorial_files/Uncertainty_Quantification" folder in my fork. But I don't think we're using the Rosenbrock.foqus file anymore. Can I delete this file?

**Comment by sotorrio1** [comment]
@fsoepyan replying to a couple of your comments:
- I agree with you that if DRMBuilder and iREVEAL are no longer part of FOQUS, we should delete those directories. 
- Regarding "Rosenbrock.foqus", I use it all the time for quick testing and stuff. Since it's not being used in any tutorial it shouldn't go in the 'tutorial_files/UQ' directory but maybe creating a 'test_files/UQ' directory and placing it there?

**Comment by anujad95** [comment]
@fsoepyan : Some comments on what you have proposed.
- Please do not delete E1 to E4 files in ALAMO since i had used them for some testing.
- Please do not delete the other heat integration example, since it is functioning well. 
- There is no tutorial for using snobfit, in the documentation. So you can move the snobfit file to the "examples/test_files/Optimization_Snobfit" folder. 
- We might want to check if the other files in "examples/Optimization" are used somewhere in the documentation or tutorials.

**Comment by fsoepyan** [comment]
- I have deleted the contents of examples/DRMBuilder, because all of these contents are available in the CCSI-Toolset/drmbuilder repo
- I have also deleted the contents of examples/iREVEAL, because the boiler.json and boiler_rom.bkp files are both in the CCSI-Toolset/iRevealLite repo, and it doesn't look like the tutorial requires the psuadeData and the results files

**Comment by fsoepyan** [comment]
- I deleted the examples/ALAMO folder, because the contents of this folder have been transferred to examples/test_files/Surrogates
- I deleted the examples/data folder, because the 1 file there (Simple_flow) has been transferred to examples/tutorial_files/Flowsheets

**Comment by fsoepyan** [comment]
- I deleted the examples/SDOE folder, because the contents of this folder have been transferred to examples/tutorial_files/SDOE

**Comment by fsoepyan** [comment]
- I deleted the contents of examples/UQ, because the contents of this folder have been transferred to examples/test_files/UQ or examples/tutorial_files/UQ

**Comment by fsoepyan** [comment]
- I deleted the contents of the examples/OUU folder, because the contents of this folder have been transferred to examples/tutorial_files/OUU

**Comment by fsoepyan** [comment]
- I deleted the content of the examples/PYOMO folder, because the 1 FOQUS file there has been transferred to examples/tutorial_files/PYOMO

**Comment by fsoepyan** [comment]
For the remaining 5 folders, I have questions:
- examples/Heat_Integration: I already transferred the contents of examples/Heat_Integration/HI_Tutorial_Eg to examples/tutorial_files/Heat_Integration . At the suggestion of @anujad95, I will not delete the rest of the files, but should I transfer these files to the examples/test_files or the examples/other_files folder?
- examples/Optimization: I already transferred the contents of examples/Optimization/Snobfit_PR_Examples to examples/test_files/Optimization_Snobfit, as suggested by @anujad95. Should I transfer the rest of the files to the examples/test_files or the examples/other_files folder?
- examples/Recycle: I already transferred the "Mass_Bal_Test_02" file to examples/tutorial_files/Flowsheets. Should I transfer the rest of the files to the examples/test_files or the examples/other_files folder?
- examples/Scaling_Spreadsheet: There is only 1 file here (scaling.xlsx), but I can't get it to open in my computer. Do we still need this file, or should we delete this file?
- examples/Smoke Tests: Should we transfer these files to the examples/test_files or the examples/other_files folder?

**Comment by sotorrio1** [comment]
It looks good to me; especially regarding OUU, UQ and SDOE files.

**Comment by anujad95** [comment]
It looks good. In examples/Heat_Integration, Optimization & Recycle, all other files can be shifted to examples/test_files. I was thinking whether we really need the other_files folder.

**Comment by fsoepyan** [comment]
@sotorrio1 and @anujad95: Thank you for the comments.
- I transferred the contents of examples/Optimization to examples/test_files/Optimization
- I transferred the contents of examples/Heat_Integration to examples/test_files/Heat_Integration
- I transferred the contents of examples/Recycle to examples/test_files/Flowsheet_with_Recycle
- I transferred the contents of examples/Smoke Tests to examples/test_files/Smoke_Tests
- I transferred the content of examples/Scaling_Spreadsheet to examples/other_files/Scaling_Spreadsheet

**Comment by fsoepyan** [comment]
- These latest changes complete the reorganization
- I will see if I can shorten the names of the subfolders within examples/tutorial_files

**Comment by fsoepyan** [comment]
- I have shortened the names of the subfolders in examples/tutorial_files
- In PR #586, I updated the documentation so that it is easier to match the subfolder with the tutorial

**Comment by ksbeattie** [comment]
@fsoepyan, are you done with this PR?  Is it still a "WIP"?

And, do both this PR and PR #586 need to be merged together?

**Comment by fsoepyan** [comment]
@ksbeattie: Yes, I am done with this PR, and yes, it would be better if both this PR and #586 are merged together. Thank you!

**Comment by anujad95** [comment]
I went through the reorganized examples folder. It all looks good. We can consider including Optimization_Snobfit within Optimization, in the test_files folder. We may also want to consider whether to keep the scaling spreadsheet in other_files. I'm not sure where it is used. If its not related to any example, we can remove it.

**Comment by ksbeattie** [comment]
> I went through the reorganized examples folder. It all looks good. We can consider including Optimization_Snobfit within Optimization, in the test_files folder. We may also want to consider whether to keep the scaling spreadsheet in other_files. I'm not sure where it is used. If its not related to any example, we can remove it.

@anujad95, could you click the review button again?  Your last review goes "stale" (in a manner of speaking) when there are new changes to the PR, so it need to be renewed.

**Pull request merged**
