### PR TITLE
Ensure that all R files are installed

### LINKED ISSUE #827: Issue generating surrogate models with ACOSSO and BSS-ANOVA
This issue was found when reproducing examples in Tutorial 2 and 3 (ACOSSO and BSS-ANOVA) in Surrogate Modeling. I got the errors below when trying to generate the surrogate model with ACOSSO and BSS-ANOVA. I temporary fixed the issues by copying the missing files (acosso_fit.R and bssanova_fit.R) to the FOQUS installation directory (“c:\anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\surrogate\acosso” and “c:\anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\surrogate\bssanova”). I found these files in FOQUS source code. It would be better to have these files installed automatically along with the FOQUS installation. 
This issue only arises when installing FOQUS directly from the command “pip install ccsi-foqus”. 

Error using ACOSSO
Traceback (most recent call last):
  File "c:\anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\surrogate\ACOSSO.py", line 172, in run
    self.setupWorkingDir()
  File "c:\anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\surrogate\ACOSSO.py", line 162, in setupWorkingDir
    shutil.copyfile(src, dest)
  File "c:\anaconda3\envs\foqus\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\anaconda3\\envs\\foqus\\lib\\site-packages\\foqus_lib\\framework\\surrogate\\acosso/acosso_fit.R'

Error using BSS-ANOVA
Traceback (most recent call last):
  File "c\anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\surrogate\BSS-ANOVA.py", line 190, in run
    self.setupWorkingDir()
  File "c\anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\surrogate\BSS-ANOVA.py", line 180, in setupWorkingDir
    shutil.copyfile(src, dest)
  File "c:\anaconda3\envs\foqus \lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\anaconda3\\envs\\foqus\\lib\\site-packages\\foqus_lib\\framework\\surrogate\\bssanova/bssanova_fit.R'

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
Should fix #827.

## Changes

In `setup.py`:

- Add `*.R` pattern to `package_data`
- Use `find_namespace_packages()` instead of `find_packages()` so that also files inside directories without `__init__.py` are included as well

### CODE REVIEW

**Review by ksbeattie — APPROVED** [review]
LGTM

**Comment by ksbeattie** [comment]
@Daison2102, use the following command, in a new conda env, to confirm that 

    pip install git+https://github.com/lbianchi-lbl/FOQUS.git@include-r-files

That will do a pip install directly from Ludovico's branch.

**Review by Daison2102 — APPROVED** [review]
Tested and issue fixed

**Comment by ksbeattie** [comment]
fyi: I've 'cherry-picked' this into the 3.7_rel branch.

**Pull request merged**
