### PR TITLE
SDoE: embedding SDoE plots into QDialog windows 

### PR DESCRIPTION
**Pull request by sotorrio1**
## Fixes/Addresses:

Attempt to fix window stack ordering embedding matplotlib plots into QDialog windows

## Summary/Motivation:
When plotting in SDoE, plots are shown as matplotlib objects and when the plots are closed the window stack ordering gets all messed up

## Changes proposed in this PR:
- returning plots as figure objects instead of using plot.show()
- creating Window class to add figure object to it

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the copyright and license terms described in the LICENSE.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by ksbeattie** [comment]
It is likely that the tests are failing here because of the changes in the way the new QDialog windows are used.  If so, then the tests themselves will need updating for this PR.

**Comment by sotorrio1** [comment]
@lbianchi-lbl was right, the problem with SDoE GUI tests was the way sdoeAnalysisDialog was getting open.

**Comment by ksbeattie** [comment]
@sotorrio1 is this ready for review now?  Were there more tests you were going to write?

**Comment by sotorrio1** [comment]
@ksbeattie Yes, it's ready for review. I added a couple of tests for plotting functions and tried to add some extra stuff into the existing GUI testing. @lbianchi-lbl might have some comments on the GUI testing stuff

**Pull request merged**
