### PR TITLE
Bringing in the python 3

### PR DESCRIPTION
**Pull request by ksbeattie**
A py2 branch has been created.

This is the merge of the python 3 work from the py3 branch into master.

Please all, review, test, etc.

### CODE REVIEW

**Comment by fsoepyan** [comment]
To test this PR, do I need to install Anaconda for Python version 3?

**Comment by CSRussell2319** [comment]
@fsoepyan, I would recommend doing that. I think you might be able to test it using a 3.x conda environment set up using Anaconda 2.7, but I'm not sure how well that works.

**Comment by fsoepyan** [comment]
- I installed Anaconda for Python version 3
- I tried to open FOQUS from this new version of Anaconda, and I got this error message:

py3_01_22_2019

**Comment by CSRussell2319** [comment]
I believe that's normal as we don't have an official py3 release of the turbine client yet

**Comment by fsoepyan** [comment]
- I did what @sotorrio1 suggests, and I can now open FOQUS. Thank you!
- I think the merge should be fine.

**Pull request merged**
