### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ksbeattie**
Addresses #521

Re-organizing and re-wording readme wrt documentation and videos in a hopefully clearer way.

### CODE REVIEW

**Comment by fsoepyan** [comment]
- The PR looks fine.
- However, the instruction for generating the html version of the documentation from Anaconda has been deleted.
- @eslickj and @anujad95: Is this OK with you? If you're fine with it, I'm fine with it.

**Comment by anujad95** [comment]
The README file seems to be good. Its fairly detailed. Adding instructions for generating the html version of the documentation would be helpful.

**Comment by ksbeattie** [comment]
Yeah, I removed the html generation bits because I felt that they aren't really needed in the top-level readme now that we have them automatically generated on readthedocs and those instructions do already exist the full documentation (for those who are interested in doing it)

**Comment by ksbeattie** [comment]
btw, I also switched the readthedocs links to point to the `stable` link (which will be the most recent release) rather than the `latest` link (which is the most recent build of master).  My thinking there is that we want people working from releases, unless they really want the latest development work in which case we can assume they know to look the latest link.

**Pull request merged**
