### PR TITLE
Change Filter Method to Use Calculated Columns

### PR DESCRIPTION
**Pull request by eslickj**
This is an update to make filtering easier to understand.  We will need to update the documentation at some point though.  This could break some of @CSRussell2319's tests if there are filter tests.

This is related to issue #312 

The box for a filter now takes a Python expression.  This expression should return a numpy array or list that has the same number of elements as rows in the data table where each entry is true or false.  True to include a row false to exclude it.  The syntax is the same as calculated columns.  There is a c("my_column") function that returns a numpy array of values in my_column. You can write your Python expression how you want, but I recommend numpy logic functions https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.logic.html.  Numpy is imported as np.

Examples  using Rosenbrock_no_vectors.foqus.

No errors and x1 > 0:

```python
np.logical_and(c("input.Rosenbrock.x1") > 0, c("err") == 0)
```
x2 > 0 and x1 > 0:

```python
np.logical_and(c("input.Rosenbrock.x1") > 0, c("input.Rosenbrock.x2") > 0)
```
x2 > 0 or x1 > 0:

```python
np.logical_or(c("input.Rosenbrock.x1") > 0, c("input.Rosenbrock.x2") > 0)
```

If you are careful with parentheses and make sure the arrays you are doing logical operations on contain strictly boolean values you can still use Python's binary operators, but be careful it's easy to get an exception or a strange result.  If you get an exception you can just go back and edit the filter.  The "and" and "or" operators will cause Numpy to raise and exception about "the truth value of an array with more than one element," so if you see that you know what you did.  These examples also work but are more error prone and less recommended.

 No errors and x1 > 0:

```python
(c("input.Rosenbrock.x1") > 0) & (c("err") == 0)
```

x2 > 0 and x1 > 0:

```python
(c("input.Rosenbrock.x1") > 0) & c("input.Rosenbrock.x2") > 0)
```
x2 > 0 or x1 > 0:

```python
(c("input.Rosenbrock.x1") > 0) | (c("input.Rosenbrock.x2") > 0)
```

### CODE REVIEW

**Comment by fsoepyan** [comment]
- I used the "examples/UQ/Rosenbrock_no_vectors" FOQUS file.
- I went to UQ, and generated and launched 50 samples successfully.
- I went back to Flowsheet, and went to the Data Table.
- When I clicked "Add/Edit Filters", a box appears:

calccol_01_24_2019

- @eslickj, can you please let me know what I need to do if I want to filter my results for outputs >= 10 and err = 0? What I typed in did not work.

**Comment by eslickj** [comment]
You don't put the calculation there.  You add a calculated column and put the name of the column there.  You can add a list of columns and they get anded together, but I don't know how useful that is.  I know it's not clear since there wasn't actually any documentation.  Can you look at the tooltips and let me know if there is a way I can improve them?

**Comment by eslickj** [comment]
@fsoepyan, I guess the way I did this was easy for me, but still probably confusing.  Let me change this so instead of using calculated columns, you can just put a Python expression right in the filer box, and I'll change the name of that box to "Filter Expression."

**Comment by eslickj** [comment]
Okay, I changed it so you can directly put in filter expressions.  I'm going to revise the pull request description, so see there for more information.

**Pull request merged**
