### PR TITLE
hiding Basic Data tab

### PR DESCRIPTION
**Pull request by sotorrio1**
hiding the basic data tab for now. I suggest after approving this PR, we close issues #176, #207, and #408

### CODE REVIEW

**Comment by fsoepyan** [comment]
- I managed to install and open this PR's version of FOQUS.
- The Basic Data button in the toolbar is gone.
- I have no problem with this PR being merged.

**Comment by sotorrio1** [comment]
@fsoepyan thanks for testing this :)

**Comment by ksbeattie** [comment]
@sotorrio1, is it possible to toggle this back on by the user?  As in without editing the code?

**Comment by sotorrio1** [comment]
@ksbeattie no, right now the only way is modifying the flag within the code, but I guess it's something doable...

**Pull request merged**
