### PR TITLE
Remove Primary Discrete Optimization Type

### PR DESCRIPTION
**Pull request by sotorrio1**
## Fixes/Addresses:

Addresses a problem raised in issue #1011 with the use of primary discrete optimization variables and triggering the use of NOMAD.

## Summary/Motivation:
While running some tests, variable type Z1d was selected by mistake and that triggered the use of NOMAD (not included in the current version of psuade-lite). We're removing the option to select Z1d type to avoid this issue until NOMAD is part of the psuade-lite external libraries again. 

## Changes proposed in this PR:
- Disabled Z1d action button
- Remove Z1d option from input table dropdown. 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the copyright and license terms described in the LICENSE.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by sotorrio1** [comment]
@dghoshal-lbl Are you sure you're testing the right branch of my fork? I just tested it and this is what I see:
Screen Shot 2022-03-22 at 1 11 56 PM

**Comment by dghoshal-lbl** [comment]
@sotorrio1 I verified the code changes in Git, which are correctly reflected on my local branch. I also see that in foqus_lib/gui/ouu/ouuSetupFrame.ui, the Z1d enabled option is set to False. So, it should be good.

I will try again starting from scratch, just to make sure I am not messing up my environments.

**Comment by dghoshal-lbl** [comment]
Worked on a new conda environment. Screenshot attached.

Screen Shot 2022-03-22 at 4 29 05 PM

**Review by dghoshal-lbl — APPROVED** [review]
Looks good.

**Pull request merged**
