### PR TITLE
SDoE: Addressing usability study findings

### PR DESCRIPTION
**Pull request by sotorrio1**
Addressing usability study findings. Fixes issue #772

### CODE REVIEW

**Review by mirandamartin — COMMENTED** [review]
Things look really good, Pedro. Just a couple of things. 
My biggest comment is that the tooltip for MWR in the Desired Design Size and NUSF Weights box didn’t pop up for me at all. 
The other thing I'll mention isn't a must-happen-now fix but a if-possible-soon fix. The bulleting and numbering in the paragraph in the Design Setup box is a little off. We meant to have an indent for the lines you numbered 1 and 2 so that it looks like it's within that bullet point. If an indent isn't possible, change lines numbered 1 and 2 to have dashes in the beginning, and removing all the bullets from the other lines would work as well. 
I'm going to also send an email with all of this info (and a visual of what I just described) so hopefully it all makes sense.

**Comment by sotorrio1** [comment]
@mirandamartin Have you hover over the label 'MWR' before the drop-downs for the MWR values? From the slides it looked you wanted the tooltip in the MWR label. If you want the tooltip for the whole group box I can change that. 
Regarding the indent, let me see what I can do.

**Comment by mirandamartin** [comment]
@sotorrio1 Oh I see what you mean. Yes I just tried it when hovering over the label 'MWR' and it worked. I think it might be better to see it when hovering over the box (or both the boxes and the label?). The powerpoint isn't clear on that, sorry!

**Review by candcook — APPROVED** [review]

**Comment by candcook** [comment]
This is looking good - I think the useability is greatly improved.

**Pull request merged**
