### PR TITLE
Updated Turbine configuration: FOQUS considers Aspen simulation successful even if there is error in Aspen

### PR DESCRIPTION
**Pull request by fsoepyan**
I updated turbineConfiguration.py, such that FOQUS will consider an Aspen Plus simulation to be successful, even though the Aspen Plus simulation reports to the user that the simulation completed with warnings and/or errors.

### CODE REVIEW

**Comment by eslickj** [comment]
I don't think we want to do this.  If the simulation ends in an error you want to know, and don't want FOQUS to say it was successful.  At least this should be optional.  This also doesn't fix the issue of results not being returned for outputs when there is an error, and warnings being mistaken for errors.

Let's hold off on this until we track down the main source of the problem.

**Comment by ksbeattie** [comment]
@eslickj says this should be addressed via #268, not this way.

**Comment by fsoepyan** [comment]
- @boverhof has fixed Issue #268 by updating TurbineLite
- Should we reject this PR and close it?

**Comment by ksbeattie** [comment]
Closing this as it was fixed by updating TurbineLite (https://github.com/CCSI-Toolset/turb_sci_gate/releases/tag/2.0.1).  See issue #268

**Pull request closed without merging**
