### PR TITLE
Fixing issue #977

### PR DESCRIPTION
**Pull request by sotorrio1**
Handling the pop up window differently and only showing up when there is any missing data. Should take care of issue #977

### CODE REVIEW

**Comment by mirandamartin** [comment]
@sotorrio1 I tested with a candidate set with (1) no missing values, (2) a few blanks in the excel sheet, and (3) those blanks changed to "NA". It worked as expected for (1) and (3), but for (2) FOQUS gave me an error, copied below. 

2021-11-10 18:26:47,484 - CRITICAL - foqus.foqus_lib.foqus - unhandled exception
Traceback (most recent call last):
  File "/Users/mgmartin/Desktop/FOQUS Other/FOQUS-sotorrio/FOQUS/foqus_lib/gui/sdoe/sdoeSetupFrame.py", line 487, in loadSimulation
    data = LocalExecutionModule.readSampleFromCsvFile(fileName, False)
  File "/Users/mgmartin/Desktop/FOQUS Other/FOQUS-sotorrio/FOQUS/foqus_lib/framework/uq/LocalExecutionModule.py", line 430, in readSampleFromCsvFile
    ) = LocalExecutionModule.readDataFromCsvFile(fileName, askForNumInputs)
  File "/Users/mgmartin/Desktop/FOQUS Other/FOQUS-sotorrio/FOQUS/foqus_lib/framework/uq/LocalExecutionModule.py", line 412, in readDataFromCsvFile
    inputArray = numpy.array(inputVals, dtype=float, ndmin=2)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (441,) + inhomogeneous part.

**Comment by sotorrio1** [comment]
@mirandamartin I just tested with NA instead of missing values and it worked for me. Would you mind sending me the exact file you're using? Thanks!

**Comment by sotorrio1** [comment]
@mirandamartin give it another try. It seems the csv.reader was ignoring the missing values and skipping to the next row. That produced an array with inconsistent shape. At first it was working on my side because my missing values were " " (one space)  and yours were "" (completely empty strings).

**Comment by mirandamartin** [comment]
@sotorrio1 I tried again and the box popped up as expected. However, then I tried to run the imputation and it completely errored out. Error message below. Since the missing values box appears to be working as expected I could approve this and open another issue for whatever is happening here if that's easier.  

2021-11-19 11:12:26,770 - CRITICAL - foqus.foqus_lib.foqus - unhandled exception
Traceback (most recent call last):
  File "/Users/mgmartin/Desktop/FOQUS Other/FOQUS-sotorrio/FOQUS/foqus_lib/gui/sdoe/sdoeSetupFrame.py", line 674, in rsVal
    _mfile = rsv.analyze()
  File "/Users/mgmartin/Desktop/FOQUS Other/FOQUS-sotorrio/FOQUS/foqus_lib/framework/uq/RSValidation.py", line 91, in analyze
    self.error_tol_percent,
  File "/Users/mgmartin/Desktop/FOQUS Other/FOQUS-sotorrio/FOQUS/foqus_lib/framework/uq/RSAnalyzer.py", line 386, in validateRS
    fname
  File "/Users/mgmartin/Desktop/FOQUS Other/FOQUS-sotorrio/FOQUS/foqus_lib/framework/uq/LocalExecutionModule.py", line 218, in readSampleFromPsuadeFile
    inputMaxs = inputMaxs + [float(values[5])]
IndexError: list index out of range

**Comment by sotorrio1** [comment]
@mirandamartin Yeah it seems this issue is fixed but whatever you are running into is a different issue with the RSAnalyzer function. I would say this specific UI issue is fixed. Please open a separate one for the last error you ran into. I didn't get it when running with one of my data imputation examples but I was able to reproduce it using your example file. I'm looking into it and trying to fix it.

**Comment by sotorrio1** [comment]
@mirandamartin it seems this is not a bug. The issue here is that your "index" column in your csv file doesn't have a header and that confuses PSUADE when reading the sample data. If you add a header (i.e. "id") to your first column, the data imputation feature should work with your blank missing values file as well.

**Comment by mirandamartin** [comment]
@sotorrio1 Right, I think we've run into this issue before. Glad it's just me and not a bug.

**Review by mirandamartin — APPROVED** [review]
Works as expected. Thanks for your patience as I worked through my issues!

**Pull request merged**
