### PR TITLE
Heat Integration Tutorial

### PR DESCRIPTION
**Pull request by anujad95**
This is a simple tutorial that explains heat integration implementation in FOQUS.

### CODE REVIEW

**Comment by fsoepyan** [comment]
When I tried to open the "Methanol" SimSinter file, I got this error message:

image

But this could be because I am using Aspen Plus v8.4 instead of v10.

But I managed to successfully upload the SimSinter json file into Turbine and FOQUS.

**Comment by fsoepyan** [comment]
However, when I tried to specify the heat integration plugin, I got this error message:

image

Can anyone please let me know what is wrong?

**Comment by fsoepyan** [comment]
@anujad95: Can you please add an image to show how a correct heat integration tag looks like in the "methanol_HI" node? I think this would be very helpful for the user following the tutorial.

**Comment by anujad95** [comment]
The error which you are getting is obtained with the old plugin. I have fixed the heat integration code in the previous PR. Did you run this with the updated FOQUS files?
In step 5 of the tutorial i have explained how to get the correct list of tags. I shall add an image to support it too.

**Comment by fsoepyan** [comment]
- I downloaded the latest version of FOQUS. The heat integration plugin now works.
- However, I can't run the Aspen file in FOQUS. I believe this is because I have Aspen v8.4 in my computer, but the example file was developed in Aspen v10.

**Comment by anujad95** [comment]
You may want to upgrade Aspen to v10, since the example file has been developed in v10. I shall add a note about this in the documentation too.

**Pull request merged**
