### PR TITLE
Optimization Plot Change

### PR DESCRIPTION
**Pull request by anujad95**
This should take care of #593 
I have also attached a simple optimization foqus file, in which the plot changes can be viewed by running the optimization.

### CODE REVIEW

**Comment by anujad95** [comment]
I have made changes only to NLOpt now. Once this is approved, i will make changes to other solvers.

**Comment by anujad95** [comment]
The changes that i have made basically create 2 optimization subplots instead of one. The first plot with red markers would depict the actual solver progress (objective function values after each function evaluation). The second plot with blue markers would depict the best values of objective function evaluated over the iterations. 
At the end of the optimization, a message would be displayed, with the iteration corresponding to the minimum objective function value.

**Comment by anujad95** [comment]
OptNewPlot

**Comment by eslickj** [comment]
This looks pretty good, but looking at the top plot, I wonder if we shouldn't use a log scale.

**Comment by anujad95** [comment]
I'm not sure if the top optimization plot has log scale. These are the actual objective function values.

**Pull request merged**
