### PR TITLE
Foqus cloud notifications

### PR DESCRIPTION
**Pull request by boverhof**
# Description
First release of FOQUS Cloud Notification Log Viewer.  Show status of several pertinent AWS resources.

### CODE REVIEW

**Review by ksbeattie — APPROVED** [review]

**Comment by boverhof** [comment]
I changed the setup dependency back to QT 5.13 rather than 5.15.

**Comment by boverhof** [comment]
@ksbeattie all tests pass.

**Comment by boverhof** [comment]
Release Notes:
- FOQUS Cloud Notification UI in the Help Menu
- Current windows displays status of Autoscaling, EC2 virtual machines, and Queues.
- To use must add a `Notification` section with `url` key to the turbine configuration file.
- FOQUS Cloud status updates are broadcast to all clients via a web socket connection.
- Web sockets are secured using `wss` protocol and utilizes Basic HTTP Authentication

**Review by ksbeattie — APPROVED** [review]
LGTM

**Pull request merged**
