### PR TITLE
Add Optional Software Install and Tutorial Notes

### PR DESCRIPTION
**Pull request by bpaul4**
## Fixes/Addresses:

Clarifies usage of Turbine and SimSinter in installation instructions, and adds a link to the relevant tutorial page.

## Changes proposed in this PR:
- Small changes to documentation pages

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the copyright and license terms described in the LICENSE.md file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by sspoon — COMMENTED** [review]
Looks good to me!

**Review by sspoon — APPROVED** [review]
Looks good!

**Comment by boverhof** [comment]
@bpaul4 I changed some text, thought it best to remove gPROMS since we haven't used this in a decade.    I'm good with it now.

**Review by boverhof — APPROVED** [review]
I changed some of the text.

**Pull request merged**
