### PR TITLE
Adding NUSF to SDoE

### PR DESCRIPTION
**Pull request by sotorrio1**
initial PR to make sure the addition of NUSF to FOQUS is not breaking anything. Related to #638

### CODE REVIEW

**Comment by ksbeattie** [comment]
@sotorrio1, your suggestion of adding `python -W ignore::FutureWarning` works.  I think if you add that to [line 35 of appveyor.yml](https://github.com/CCSI-Toolset/FOQUS/blob/master/appveyor.yml#L35), that should get AppVeyor to pass.

Any luck on getting someone to review this PR, so we can merge it and get a possible RC cut?

**Comment by candcook** [comment]
This has a lot of features added - looking good

**Comment by sotorrio1** [comment]
@ksbeattie I'm not sure I'm using the -W flag for ignoring the warnings correctly. Would you mind reviewing the changes to the  [line 35 of appveyor.yml](https://github.com/CCSI-Toolset/FOQUS/blob/master/appveyor.yml#L35)
Thanks!

**Comment by sotorrio1** [comment]
@ksbeattie never mind, it looks like AppVeyor passed.

**Pull request merged**
