### PR TITLE
Address failures in nightly builds for Python 3.8 on Windows

### PR DESCRIPTION
**Pull request by lbianchi-lbl**

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
The last failing checks are addressed by #936, which should be merged first.

**Comment by lbianchi-lbl** [comment]
@ksbeattie it looks like in #936 I did everything that was needed to be able to pin the pip version before FOQUS is installed... except actually doing the pinning. I didn't realize the pinning was missing when merging #936 and I believe this was the reason the checks runs on `master` weren't working. Sorry about the confusion!

I've now added the pinning in 69b5510 and now all checks are running (and passing) as expected, and this should be ready to be merged.

**Comment by lbianchi-lbl** [comment]
@sotorrio1 Merging this in should fix the pip issues you're encountering on #938. It just needs a review before being automerged.

**Review by sotorrio1 — APPROVED** [review]
LGTM

**Comment by sotorrio1** [comment]
@lbianchi-lbl Thanks! Just updated my branch and the checks started running again.

**Pull request merged**
