### PR TITLE
Fixed optimization generate samples dialog.

### PR DESCRIPTION
**Pull request by eslickj**
Parent argument was missing from dialog box init function.  Issue #310

### CODE REVIEW

**Comment by fsoepyan** [comment]
- I tested this PR using the "examples/UQ/Rosenbrock_no_vectors" FOQUS file
- In Optimization, I set x2 and x3 as samples
- When I tried to generate samples, I got this error message:

opt_01_24_2019

**Comment by eslickj** [comment]
@fsoepyan, I think what happened here is that you  tried you do a full factorial sampling and entered single values.  The input for those is lists.  I guess we probably ought to have some error checking and some extra information on the page.  Will add.

It works like this: x1 = [2, 4], x2 = [1,3] samples = [[2,1], [2,3], [4,1], [4,3]]

**Comment by eslickj** [comment]
I added a check to catch the error @fsoepyan encountered that tells you exactly what you did wrong, and how to fix it.

**Comment by eslickj** [comment]
I'll fix this one here too.  It's a problem left over from the Python 3 conversion.

**Comment by eslickj** [comment]
@fsoepyan, I fixed and tested the read from file problem.  I'll merge this.  If you have any other problems go ahead and submit new issues.

**Pull request merged**
