### PR TITLE
Add GUI tests and test framework based on pytest-qt plugin

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## Summary

- This PR is the first step towards implementing tests targeting the FOQUS GUI that are fully integrated with the pytest framework
- The tests are implementing using the third-party `pytest-qt` framework, plus a set of extensions (tentatively named `pytest_qt_extras`) that is being developed as a higher-level wrapper around `pytest-qt`
- These extensions allow writing GUI tests with a more concise and natural syntax, with the goal of making writing tests for FOQUS more efficient and convenient
- The ultimate goal of this improved test setup is to facilitate extending the FOQUS test suite towards a more complete coverage of the codebase

### A: Verify that the new GUI tests work properly on your machine

- Checkout the code from this PR, navigate to the root of the repository, then:

    ```sh
    # activate Conda env
    conda activate ccsi-foqus  # or create new Conda environment
    # install dev dependencies
    pip install -r requirements-dev.txt
    # install PSUADE
    conda install -c conda-forge -c CCSI-Toolset psuade-lite
    # check that psuade is installed
    psuade --help
    ```
- Run the GUI tests:

    ```sh
    pytest --slowdown-wait=200 -sv -x tests-gui/
    ```

  - This should take a few minutes
    - The `-x` flag makes pytest exit immediately after the first failure
  - The FOQUS main window will be opened and run through the actions defined in the tests "by itself" (i.e. no manual intervention should be necessary)
  - The *action* currently being executed will be displayed as a red rectangle around the action's target widget and a label with the action's name
  - Specify a different value for `--slowdown-wait` (in ms) to run the tests so that they appear slower or faster
- There should now be a `.pytest-artifacts` subdirectory, containing these two subdirectories:
  - `foqus_working_dir`, containing the files produced by FOQUS during the test run
  - `screenshots`, containing the screenshots that were generated automatically before and after each action
  - `snapshots`, containing a set of specialized "data dumps" of a parent widget and all its children, used for debugging issues with locating widgets

### CODE REVIEW

**Comment by boverhof** [comment]
@lbianchi-lbl think you meant `tests-gui` rather than `gui-tests`

**Comment by boverhof** [comment]
# Test Failure tests-guid

```
(foqus-issue-916) C:\Users\Administrator\Desktop\FOQUS-lbianchi>pytest --slowdown-wait=200 -sv -x tests-gui
================================================= test session starts =================================================
platform win32 -- Python 3.7.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- c:\programdata\anaconda3\envs\foqus-issue-916\python.exe
cachedir: .pytest_cache
PyQt5 5.13.0 -- Qt runtime 5.13.0 -- Qt compiled 5.13.0
rootdir: C:\Users\Administrator\Desktop\FOQUS-lbianchi, configfile: pytest.ini
plugins: cov-2.12.1, qt-4.0.2
collected 9 items

tests-gui/test_uq.py::TestUQ::test_generate_samples[UQ/Rosenbrock.foqus] ERROR

======================================================= ERRORS ========================================================
_________________________ ERROR at setup of TestUQ.test_generate_samples[UQ/Rosenbrock.foqus] _________________________

    @pytest.fixture(scope='session')
    def psuade_path():
        _psuade_path = shutil.which('psuade')
>       assert _psuade_path is not None
E       assert None is not None

tests-gui\conftest.py:71: AssertionError
=============================================== short test summary info ===============================================
ERROR tests-gui/test_uq.py::TestUQ::test_generate_samples[UQ/Rosenbrock.foqus] - assert None is not None
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================== 1 error in 1.48s ===================================================

(foqus-issue-916) C:\Users\Administrator\Desktop\FOQUS-lbianchi>
```

**Comment by lbianchi-lbl** [comment]
> @lbianchi-lbl think you meant `tests-gui` rather than `gui-tests`

Thanks, good catch. Fixed.

**Comment by lbianchi-lbl** [comment]
@boverhof thanks for trying this. I can't reproduce the error. That part of `conftest.py` creates the FOQUS main dir, i.e. in first approximation it's not doing anything different than calling `foqus` from the command line (or, more accurately, `from foqus_lib import foqus; foqus()`).

Can you test if you get the `ImportError` in any other way? e.g.:

```sh
python -c 'from foqus_lib import foqus`
python -c 'from foqus_lib.framework.sintervectorize.SinterFileVectorize import *'
```

**Review by sotorrio1 — APPROVED** [review]
LG(reat)TM. It's pretty cool to see the test going through the whole tutorial in a matter of seconds. I love the amount of screenshots as well :)

**Review by ksbeattie — APPROVED** [review]
LGTM

**Comment by lbianchi-lbl** [comment]
@ksbeattie I had to fix some unexpected incompatibilities on Python 3.6; in the end I just added a marker to skip the `pytest-qt` part with a message if the GUI tests are run on 3.6. All the checks pass so we should be good to go!

**Review by ksbeattie — DISMISSED** [review]
LGTM

**Review by ksbeattie — APPROVED** [review]
LGTM

**Pull request merged**
