### PR TITLE
Added pandas version requirement for setup.py

### PR DESCRIPTION
**Pull request by fsoepyan**
This change is also for issue #222

### CODE REVIEW

**Comment by fsoepyan** [comment]
John (@eslickj), I'm not sure if this is correct, but can you please check? Thank you.

**Comment by eslickj** [comment]
The ==0.23 should go inside the quotes at least (I think 'pandas'==.23 probably just evaluates to false).  I'm not really sure about the format, but I think that's right if you fix the quotes.  You'll have to run your version of setup.py to make sure it works as expected.

**Comment by fsoepyan** [comment]
- I moved the ==.23 inside the quotes
- The previous code results in error, but the new code is fine, I think

pandas_06_19_2018

**Comment by fsoepyan** [comment]
- I uninstalled Pandas using Anaconda by typing: pip uninstall pandas
- I had pandas-0.22.0
- Then, I reinstalled Pandas by typing: python setup.py develop
- The setup was successful
- I checked my version of Pandas, and I now have Pandas version 0.23.1
- This should take care of Issue #222
- I will test FOQUS and let you know what happens

**Comment by fsoepyan** [comment]
- I managed to save and open a FOQUS file
- I think once this PR is merged, we can close issue #222

**Comment by eslickj** [comment]
Looks good.

**Pull request merged**
