### PR TITLE
Update ouuSetupFrame.py

### PR DESCRIPTION
**Pull request by sotorrio1**
cleaning up psuade files 'psuadeEval.out.xxx'

This should take care of issue #146

### CODE REVIEW

**Comment by fsoepyan** [comment]
I tried to open FOQUS from this PR, I got this error message, and FOQUS failed to open:

ouu_01_14_2019

**Comment by sotorrio1** [comment]
@fsoepyan sorry Byron, try now. I forgot a stupid colon...

**Comment by fsoepyan** [comment]
@sotorrio1, thank you for the fix.

Unfortunately, when I tried to open FOQUS from the updated PR, I got another error message, and FOQUS failed to open:

ouu_01_15_2019

**Comment by sotorrio1** [comment]
@fsoepyan that's weird, I didn't modify that line at all...

**Comment by sotorrio1** [comment]
@fsoepyan  wow, it looks like I'm losing it... try now, please. I'm sorry about the whole back and forth

**Pull request merged**
