### PR TITLE
Add SDOE IRSF Example csv file

### PR DESCRIPTION
**Pull request by mirandamartin**
Adding csv to Examples folder for SDOE IRSF

### CODE REVIEW

**Comment by mirandamartin** [comment]
I had created a partial "basics-inputresponse" document in the master but then created a new branch for it where the actual document is. So I went back and deleted the "basics" document in master/this branch. Please ignore!

**Review by sotorrio1 — DISMISSED** [review]
LGTM

**Comment by mirandamartin** [comment]
Deleted all the figure files, so this should only be adding the csv now

**Review by ksbeattie — APPROVED** [review]
LGTM

**Pull request merged**
